name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Envoyer message Discord si succès
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ Oh putaing ! J'ai réussi les tests sur ${GITHUB_REPOSITORY} (${GITHUB_REF_NAME}) par ${GITHUB_ACTOR} !\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
      
      - name: Envoyer message Discord si échec
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"❌ Oh merde ! Tests échoués sur ${GITHUB_REPOSITORY} (${GITHUB_REF_NAME}) par ${GITHUB_ACTOR}... Vérifie les logs CI.\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
